name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master, develop]

jobs:
  website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [hoprnet-org]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.9.1
      - name: Cache components node_modules
        id: cache-components-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: components-build-${{ hashFiles('packages/components/package.json') }}
      - name: Cache ${{ matrix.site }} node_modules
        id: cache-${{ matrix.site }}-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.site }}-build-${{ hashFiles(matrix.site + 'package.json') }}
      - name: Install node modules
        if: steps.cache-components-modules.outputs.cache-hit != 'true' || steps.cache-${{ matrix.site }}-modules.outputs.cache-hit != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn bootstrap
      - name: Prebuild website for production
        working-directory: websites/${{ matrix.site }}
        run: yarn build
      - name: Deploy website to Vercel (staging)
        if: github.ref != 'refs/heads/master'
        working-directory: websites/${{ matrix.site }}
        run: npx now -t ${{ secrets.NOW_DEPLOYMENT_TOKEN }} -A now.json -c --scope hoprnet
      - name: Deploy website to Vercel (production)
        if: github.ref == 'refs/heads/master'
        working-directory: websites/${{ matrix.site }}
        run: npx now -t ${{ secrets.NOW_DEPLOYMENT_TOKEN }} -A now.json -c --scope hoprnet --prod
